# PRODUCT: 판매중인 상품 정보
# - 상품 ID, 상품 코드, 판매가
# OFFLINE_SALE: 오프라인 상품 판매 정보
# - 오프라인 상품 판매 id, 상품 id, 판매량, 판매일 

# PRODUCT 테이블과 OFFLINE_SALE테이블에서 상푸모드 별 매출액 

SELECT 
    PRODUCT_CODE
    , SUM(SALES_AMOUNT * PRICE) AS SALES
FROM OFFLINE_SALE OS

JOIN PRODUCT PD ON PD.PRODUCT_ID = OS.PRODUCT_ID 
GROUP BY PRODUCT_CODE

ORDER BY SALES DESC, PRODUCT_CODE
