SELECT 
    DISTINCT D.ID
    , D.EMAIL
    , D.FIRST_NAME
    , D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S ON S.CODE = (S.CODE & D.SKILL_CODE)
WHERE S.CODE = 256 OR S.CODE = 1024
ORDER BY D.ID;

