SELECT 
C.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE car_type = '세단' AND MONTH(start_date) = 10
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;