-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) FROM FIRST_HALF F

JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR

GROUP BY INGREDIENT_TYPE

# 상반기 동안 아이스크림 성분 타입, INGREDIENT_TYPE
# 성분 타입에 대한 아이스크림의 총 주문량, TOTAL_ORDER


