SELECT FA.CATEGORY
     , FA.PRICE AS MAX_PRICE
     , FA.PRODUCT_NAME
FROM FOOD_PRODUCT FA

WHERE FA.CATEGORY IN ('과자', '국', '김치', '식용유')
  AND FA.PRICE = (
       SELECT MAX(FB.PRICE)
       FROM FOOD_PRODUCT FB
       WHERE FA.CATEGORY = FB.CATEGORY
     )
     
ORDER BY 2 DESC;
