SELECT 
    CASE 
        WHEN SUM(CASE WHEN SC.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
         AND SUM(CASE WHEN SC.NAME = 'Python' THEN 1 ELSE 0 END) > 0
        THEN 'A' 
        WHEN SUM(CASE WHEN SC.NAME = 'C#' THEN 1 ELSE 0 END) > 0
        THEN 'B'
        WHEN SUM(CASE WHEN SC.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
        THEN 'C'
    ELSE NULL
    END AS GRADE
    , DP.ID
    , DP.EMAIL
FROM DEVELOPERS DP

JOIN SKILLCODES SC ON (SC.CODE & DP.SKILL_CODE) = SC.CODE
GROUP BY DP.ID, DP.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY 1, 2;